networks:
  traefik-net:
    external: true

services:
  app:
    image: ghcr.io/larsluph/omv-power-proxy:latest
    container_name: omv-power-proxy
    restart: unless-stopped
    network_mode: host
    env_file: .env
    volumes:
      - "./config:/data"
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.omv-power-proxy.rule=Host(`power.larsluph.dev`)"
      - "traefik.http.routers.omv-power-proxy.entrypoints=websecure"
      - "traefik.http.routers.omv-power-proxy.tls=true"
      - "traefik.http.services.omv-power-proxy.loadbalancer.server.port=5656"

